### ISSUE TITLE
Add Temporary Blackouts

### ISSUE THREAD

**Issue by IOxeOfficial** [justalemon/SimpleSync#23]
Could there be a way to generate a system that allows automatic BlackOut every x hours?

**Comment by justalemon** [comment]
I have been working on this for the last couple of hours.

![image](https://user-images.githubusercontent.com/11861253/79214292-9a399000-7e18-11ea-9a47-6d4efa89fdef.png)

![image](https://user-images.githubusercontent.com/11861253/79214301-9dcd1700-7e18-11ea-8d47-9c5c5a46667d.png)
