### ISSUE TITLE
So heavy resource

### ISSUE THREAD

**Issue by gunsela92** [justalemon/SimpleSync#28]
I made the settings of time and weather but it seems like the resource is so heavy

![image](https://user-images.githubusercontent.com/11861253/79077217-da402c00-7ccd-11ea-99c1-d1fa772c7d9d.png)

**Comment by justalemon** [comment]
What settings did you change? What are the specifications of the machine that you are using?

**Comment by gunsela92** [comment]
I just set my weather to Istanbul and timezone. My specs are Xeon 2288G 4 Cores, 16 GB Ram 1 gbps network speed

**Comment by justalemon** [comment]
I would say that this is normal because we need to get the weather every minute and the time every second. Sadly, it does not say what tick is having problems.

**Comment by xrtw** [comment]
yes for me also high tick rates.. sorry no repro have

**Comment by JSanchezFDZ** [comment]
I also think this script is too heavy. Has an excess of consumption.

Could you add that it checks the weather every X time? Thus we would save consumption.

Sorry for my bad english

**Comment by xrtw** [comment]
yeah went back to vSync... so much using in profiler this SimpleSync

**Comment by justalemon** [comment]
Sadly, FiveM does not support the debugging of game scripts, so I can't know what function or native call is using too much memory.

Also, don't rely on the profiler too much, as this also takes native calls into consideration and this might be the problem in this case.

> Could you add that it checks the weather every X time?

Can you create a new issue for this feature request please.
