### ISSUE TITLE
blinking every evening at 20:00 21:00 22:00

### ISSUE THREAD

**Issue by xrtw** [justalemon/SimpleSync#72]
https://gyazo.com/224a0d4e40654197f97497115f820fa5 here it is.

**Comment by justalemon** [comment]
We need more information, like:

* What are your settings?
* What version are you using?
* What resources are you running in the server?

**Comment by xrtw** [comment]
sorry.
set simplesync_timezone "FLE Standard Time"
set simplesync_city "Vilnius, LT"
set simplesync_modetime 2
set simplesync_modeweather 1
set simplesync_key "0af4d77217caf3e75b17aa4ef43b0ada"

**Comment by justalemon** [comment]
What resources are you running? You can get this information by visiting the IP of your server with info.json added at the end, like this: http://127.0.0.1:30120/info.json

You will see something like this, copy and paste it here:

```
"resources":["hardcap","spawnmanager","_cfx_internal","fivem-map-skater","monitor","basic-gamemode","playernames","webadmin","chat","mapmanager","rconlog","scoreboard","sessionmanager","fivem"]
```

**Comment by xrtw** [comment]
> What resources are you running? You can get this information by visiting the IP of your server with info.json added at the end, like this: http://127.0.0.1:30120/info.json
> 
> You will see something like this, copy and paste it here:
> 
> ```
> "resources":["hardcap","spawnmanager","_cfx_internal","fivem-map-skater","monitor","basic-gamemode","playernames","webadmin","chat","mapmanager","rconlog","scoreboard","sessionmanager","fivem"]
> ```

http://91.211.247.237:30120/info.json

**Comment by justalemon** [comment]
I'm closing this issued because the list of resources was never posted.
