### ISSUE TITLE
Unable to load Timezones

### ISSUE THREAD

**Issue by JayG-EBSCO** [justalemon/SimpleSync#73]

**Comment by JayG-EBSCO** [comment]
I love the idea of being able to sync with a specified timezone, but I cannot seem to get it to work. I am running with the following in my server.cfg to attempt and set the time.

```
# simplesync presets
set simplesync_modetime 2
set simplesync_timezone "America/New_York"
ensure SimpleSync
```

The console output from the server is consistently showing:
```
Use the command /timezones to see the available TZs
Just in case, we changed the TZ to 'America/Los_Angeles' 
```

If I try and use the /timezones command in game to get a list of the time zones, it does not return anything.

I am running my server as a Docker container. The container has its time zone set to "Americas/New_York". The container is based on Alpine Linux, and the Docker host is running Ubuntu 20.04.

**Comment by jaysgrant** [comment]
I figured out my issue here. The container did not have tzdata installed. I can now set the time zone.  The issue I am having now is that it is 5 hours ahead, appearing to be stuck on UTC time, while I am seeking America/New_York. I've verified via console on the docker host, and within the container that the local timezone is America/New_York.

**Comment by justalemon** [comment]
As this appears to be a problem with the container that you were using (I would guess that you are using Docker), this is not a problem with SimpleSync so I'm closing the issue as invalid.
