### ISSUE TITLE
Weather Export

### ISSUE THREAD

**Issue by kevingorman1000** [justalemon/SimpleSync#76]
Hello,

We are currently trying to get the exports for the "setWeather" to work.

However, whatever we do, doesn't seem to get it to change the weather. We have got "setTime" to work fine, What is confusing us, is the fact that it requires a bool, however this doesn't make sense to us. Can you please explain how to use the "setWeather" export?

We are using Lua.

Thanks

**Comment by justalemon** [comment]
Hi, I answered to you in Discord but I'm going to post it here for others to see.

The exports are called in lua like any other export, just make sure that the resource name is set to **simplesync** (in lowercase).

This is a quick example that you can use for setWeather:

```lua
exports.simplesync:setWeather("XMAS")
```
