### ISSUE TITLE
water and really dark in some shells

### ISSUE THREAD

**Issue by maxcamorra** [justalemon/SimpleSync#78]
In some shells I have a problem that there is water on the floor and some of shells are extremely dark. How to change it? I use real sync for weather and time.
![image](https://user-images.githubusercontent.com/78707245/122986134-4e309680-d39f-11eb-970a-29d5bd05f636.png)

**Comment by justalemon** [comment]
I don't understand the problem.  Can you please elaborate.

**Comment by maxcamorra** [comment]
Its crazy dark inside the shell. Is it because of the sync script? or why is the shell so damn dark?

**Comment by justalemon** [comment]
That is Franklin's Forum Drive Safehouse. Maybe you loaded the house incorrectly causing this issue.
